import { inMemoryStore } from './db.js';

export function seedInitialData() {
  // Clear and populate initial data
  inMemoryStore.users = [
    {
      id: 'usr-admin-01',
      username: 'admin.edoc',
      email: 'admin.edoc@ku.th',
      role: 'admin',
      auth_provider: 'ku_alllogin',
      first_name_th: 'ผู้ดูแลระบบ',
      last_name_th: 'ทะเบียนและประมวลผล',
      phone_number: '042-725000',
      is_verified: true,
      created_at: new Date(),
    },
    {
      id: 'usr-staff-01',
      username: 'staff.counter',
      email: 'staff.counter@ku.th',
      role: 'staff',
      auth_provider: 'ku_alllogin',
      first_name_th: 'สมศรี',
      last_name_th: 'บริการดีเลิศ',
      phone_number: '042-725001',
      is_verified: true,
      created_at: new Date(),
    },
    {
      id: 'usr-exec-01',
      username: 'exec.dean',
      email: 'exec.dean@ku.th',
      role: 'executive',
      auth_provider: 'ku_alllogin',
      first_name_th: 'รองศาสตราจารย์ ดร.',
      last_name_th: 'ผู้บริหาร มก.ฉกส.',
      phone_number: '042-725002',
      is_verified: true,
      created_at: new Date(),
    },
    {
      id: 'usr-student-01',
      username: '6540201234',
      email: 'nontri.i@ku.th',
      role: 'student',
      auth_provider: 'ku_alllogin',
      student_id: '6540201234',
      first_name_th: 'นนทรี',
      last_name_th: 'อีสานงาม',
      phone_number: '0812345678',
      citizen_id: '1479900123456',
      status_code: 'S',
      is_verified: true,
      created_at: new Date(),
    },
    {
      id: 'usr-alumni-01',
      username: 'somwang.graduate@gmail.com',
      email: 'somwang.graduate@gmail.com',
      role: 'student',
      auth_provider: 'google',
      student_id: '6240208899',
      first_name_th: 'สมหวัง',
      last_name_th: 'เรียนจบแล้ว',
      phone_number: '0855554444',
      citizen_id: '1479900999999',
      status_code: 'G',
      is_verified: true,
      created_at: new Date(),
    },
  ];

  inMemoryStore.documentTypes = [
    {
      id: 'doc-01',
      code: 'TRANSCRIPT_TH',
      name_th: 'ใบแสดงผลการศึกษา (Transcript) ภาษาไทย',
      name_en: 'Academic Transcript (Thai)',
      description: 'ใบรายงานผลการศึกษาตลอดหลักสูตรฉบับภาษาไทย พร้อมตราประทับมหาวิทยาลัย',
      price: 50.00,
      format: 'both',
      allowed_statuses: ['S', 'D', 'G'],
      processing_days: 2,
      is_active: true,
    },
    {
      id: 'doc-02',
      code: 'TRANSCRIPT_EN',
      name_th: 'ใบแสดงผลการศึกษา (Transcript) ภาษาอังกฤษ',
      name_en: 'Academic Transcript (English)',
      description: 'Official Academic Transcript in English with University Seal',
      price: 50.00,
      format: 'both',
      allowed_statuses: ['S', 'D', 'G'],
      processing_days: 2,
      is_active: true,
    },
    {
      id: 'doc-03',
      code: 'CERT_STUDENT_STATUS_TH',
      name_th: 'หนังสือรับรองการเป็นนิสิต ภาษาไทย',
      name_en: 'Certificate of Student Status (Thai)',
      description: 'รับรองสถานภาพการเป็นนิสิตปัจจุบัน สำหรับยื่นขอทุนหรือทำธุรกรรม',
      price: 30.00,
      format: 'both',
      allowed_statuses: ['S', 'D'],
      processing_days: 1,
      is_active: true,
    },
    {
      id: 'doc-04',
      code: 'CERT_STUDENT_STATUS_EN',
      name_th: 'หนังสือรับรองการเป็นนิสิต ภาษาอังกฤษ',
      name_en: 'Certificate of Student Status (English)',
      description: 'Official Student Status Certificate in English for Visa/Scholarships',
      price: 30.00,
      format: 'both',
      allowed_statuses: ['S', 'D'],
      processing_days: 1,
      is_active: true,
    },
    {
      id: 'doc-05',
      code: 'CERT_EXPECTED_GRAD',
      name_th: 'หนังสือรับรองคาดว่าจะสำเร็จการศึกษา',
      name_en: 'Certificate of Expected Graduation',
      description: 'สำหรับนิสิตชั้นปีสุดท้ายที่กำลังจะจบการศึกษาในภาคเรียนปัจจุบัน',
      price: 40.00,
      format: 'both',
      allowed_statuses: ['S'],
      processing_days: 2,
      is_active: true,
    },
    {
      id: 'doc-06',
      code: 'CERT_GRADUATION_TH',
      name_th: 'หนังสือรับรองสำเร็จการศึกษา ภาษาไทย',
      name_en: 'Certificate of Graduation (Thai)',
      description: 'รับรองการสำเร็จการศึกษาและได้รับอนุมัติปริญญาแล้ว',
      price: 50.00,
      format: 'both',
      allowed_statuses: ['G'],
      processing_days: 2,
      is_active: true,
    },
    {
      id: 'doc-07',
      code: 'CERT_GRADUATION_EN',
      name_th: 'หนังสือรับรองสำเร็จการศึกษา ภาษาอังกฤษ',
      name_en: 'Certificate of Graduation (English)',
      description: 'Official Certificate of Graduation in English',
      price: 50.00,
      format: 'both',
      allowed_statuses: ['G'],
      processing_days: 2,
      is_active: true,
    },
    {
      id: 'doc-08',
      code: 'COURSE_DESC_TH',
      name_th: 'คำอธิบายรายวิชา (Course Description)',
      name_en: 'Course Description',
      description: 'รายละเอียดเนื้อหารายวิชาสำหรับเทียบโอนหน่วยกิตหรือศึกษาต่อ',
      price: 100.00,
      format: 'hardcopy',
      allowed_statuses: ['S', 'D', 'G'],
      processing_days: 3,
      is_active: true,
    },
  ];

  inMemoryStore.documentPackages = [
    {
      id: 'pkg-01',
      code: 'PKG_GRAD_BUNDLE',
      name_th: '🎓 ชุดแพ็กเกจผู้สำเร็จการศึกษา (Graduation Bundle)',
      description: 'รวม Transcript ไทย 1 ฉบับ + Transcript อังกฤษ 1 ฉบับ + ใบรับรองสำเร็จการศึกษา ไทยและอังกฤษ อย่างละ 1 ฉบับ (รวม 4 ฉบับ)',
      package_price: 160.00,
      is_restricted_whitelist: false,
      allowed_statuses: ['G'],
      is_active: true,
      items: [
        { document_type_id: 'doc-01', quantity: 1, name_th: 'Transcript ภาษาไทย' },
        { document_type_id: 'doc-02', quantity: 1, name_th: 'Transcript ภาษาอังกฤษ' },
        { document_type_id: 'doc-06', quantity: 1, name_th: 'หนังสือรับรองสำเร็จการศึกษา ภาษาไทย' },
        { document_type_id: 'doc-07', quantity: 1, name_th: 'หนังสือรับรองสำเร็จการศึกษา ภาษาอังกฤษ' },
      ],
    },
    {
      id: 'pkg-02',
      code: 'PKG_INTERN_BUNDLE',
      name_th: '💼 ชุดแพ็กเกจสมัครฝึกงาน/สหกิจศึกษา (Internship Bundle)',
      description: 'รวม Transcript ไทย 1 ฉบับ + หนังสือรับรองการเป็นนิสิต 1 ฉบับ พร้อมยื่นสถานประกอบการ',
      package_price: 65.00,
      is_restricted_whitelist: false,
      allowed_statuses: ['S'],
      is_active: true,
      items: [
        { document_type_id: 'doc-01', quantity: 1, name_th: 'Transcript ภาษาไทย' },
        { document_type_id: 'doc-03', quantity: 1, name_th: 'หนังสือรับรองการเป็นนิสิต ภาษาไทย' },
      ],
    },
    {
      id: 'pkg-03',
      code: 'PKG_HONOR_SCHOLAR',
      name_th: '⭐ แพ็กเกจนิสิตเกียรตินิยม/ทุนการศึกษา (เฉพาะรายชื่อที่กำหนด)',
      description: 'เอกสารชุดพิเศษสำหรับนิสิตที่ผ่านการอนุมัติเกียรตินิยมและได้รับยกเว้นค่าธรรมเนียมบางส่วน (กำหนดสิทธิ์ด้วยรายชื่อ Excel)',
      package_price: 50.00,
      is_restricted_whitelist: true,
      allowed_statuses: ['G'],
      is_active: true,
      items: [
        { document_type_id: 'doc-01', quantity: 2, name_th: 'Transcript ภาษาไทย (2 ฉบับ)' },
        { document_type_id: 'doc-02', quantity: 2, name_th: 'Transcript ภาษาอังกฤษ (2 ฉบับ)' },
      ],
    },
  ];

  // Whitelist sample for pkg-03
  inMemoryStore.packageWhitelist = [
    { package_id: 'pkg-03', student_id: '6240208899', full_name: 'นายสมหวัง เรียนจบแล้ว' },
  ];

  // Initial Sample Requests for Dashboards
  inMemoryStore.documentRequests = [
    {
      id: 'req-1001',
      order_no: 'EDOC-20260905-001',
      user_id: 'usr-student-01',
      student_id: '6540201234',
      student_name: 'นาย นนทรี อีสานงาม',
      student_status: 'S',
      faculty_name: 'คณะวิทยาศาสตร์และวิศวกรรมศาสตร์',
      department_name: 'ภาควิชาวิศวกรรมคอมพิวเตอร์และสารสนเทศ',
      delivery_method: 'pickup',
      shipping_fee: 0.00,
      subtotal: 80.00,
      total_amount: 80.00,
      status: 'completed',
      created_by_role: 'student',
      created_at: new Date(Date.now() - 24 * 3600 * 1000),
      items: [
        { item_name: 'ใบแสดงผลการศึกษา (Transcript) ภาษาไทย', unit_price: 50, quantity: 1, amount: 50 },
        { item_name: 'หนังสือรับรองการเป็นนิสิต ภาษาไทย', unit_price: 30, quantity: 1, amount: 30 },
      ],
    },
    {
      id: 'req-1002',
      order_no: 'EDOC-20260906-002',
      user_id: 'usr-alumni-01',
      student_id: '6240208899',
      student_name: 'นาย สมหวัง เรียนจบแล้ว',
      student_status: 'G',
      faculty_name: 'คณะทรัพยากรธรรมชาติและอุตสาหกรรมเกษตร',
      department_name: 'ภาควิชาเกษตรศาสตร์',
      delivery_method: 'postal',
      recipient_name: 'สมหวัง เรียนจบแล้ว',
      shipping_address: '123/45 ถนนเจริญเมือง ต.ธาตุเชิงชุม อ.เมือง จ.สกลนคร 47000 (โทร 0855554444)',
      shipping_fee: 50.00,
      subtotal: 160.00,
      total_amount: 210.00,
      status: 'processing',
      postal_tracking_no: 'ED123456789TH',
      created_by_role: 'student',
      created_at: new Date(Date.now() - 2 * 3600 * 1000),
      items: [
        { item_name: '🎓 ชุดแพ็กเกจผู้สำเร็จการศึกษา (Graduation Bundle)', unit_price: 160, quantity: 1, amount: 160 },
      ],
    },
    {
      id: 'req-1003',
      order_no: 'EDOC-20260906-003',
      user_id: 'usr-staff-01',
      student_id: '6440205678',
      student_name: 'นางสาว สกลนคร สุขสวัสดิ์',
      student_status: 'D',
      faculty_name: 'คณะศิลปศาสตร์และวิทยาการจัดการ',
      department_name: 'ภาควิชาการบัญชีและการเงิน',
      delivery_method: 'pickup',
      shipping_fee: 0.00,
      subtotal: 30.00,
      total_amount: 30.00,
      status: 'ready_for_pickup',
      created_by_role: 'counter_staff',
      counter_staff_id: 'usr-staff-01',
      created_at: new Date(Date.now() - 1 * 3600 * 1000),
      items: [
        { item_name: 'หนังสือรับรองการเป็นนิสิต ภาษาไทย', unit_price: 30, quantity: 1, amount: 30 },
      ],
    },
  ];

  console.log('🌱 [Database] Initial seed data loaded successfully into memory store.');
}
